/* ESTRUCTURAS DE DATOS Y ALGORITMOS II
* ENUNCIADO: PROBLEMA N REINAS
* ASUNTO: ESTE PROGRAMA ENCUENTRA LAS POSIBLES SOLUCIONES PARA EL PROBLEMA DE LAS N REINAS
AUTORES: ANGEL MORENO ID:1104666
*        GLEIDY ESPINAL ID:1104225
*        ALLEN SILVERIO ID:1104220
*        CRISTIAN JIMÉNEZ ID:1106166
*        WILLIAM FERREIRA ID:1104228
* FECHA: 24/11/2022
*/
#include <iostream>
#include <conio.h>
#include <string>

using namespace std;

int main() {

}